// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// meanshift
List meanshift(NumericVector array, int radiusS, double radiusR, unsigned int minDensity, unsigned int speedUp);
RcppExport SEXP _rmeanshift_meanshift(SEXP arraySEXP, SEXP radiusSSEXP, SEXP radiusRSEXP, SEXP minDensitySEXP, SEXP speedUpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type array(arraySEXP);
    Rcpp::traits::input_parameter< int >::type radiusS(radiusSSEXP);
    Rcpp::traits::input_parameter< double >::type radiusR(radiusRSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type minDensity(minDensitySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type speedUp(speedUpSEXP);
    rcpp_result_gen = Rcpp::wrap(meanshift(array, radiusS, radiusR, minDensity, speedUp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rmeanshift_meanshift", (DL_FUNC) &_rmeanshift_meanshift, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmeanshift(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
